services:
  pythontelegrambottemplate:
    image: ghcr.io/daniil-leshchev/google-sheets-expenses-bot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      BOT_TOKEN
      GOOGLE_CREDENTIALS
      AUTHORIZED_USER
    volumes:
      - ./data:/app/data
    restart: unless-stopped
