services:
  pythontelegrambottemplate:
    image: ghcr.io/daniil-leshchev/google-sheets-expenses-bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GOOGLE_CREDENTIALS=${GOOGLE_CREDENTIALS}
      - AUTHORIZED_USER=${AUTHORIZED_USER}
    volumes:
      - ./data:/app/data
    restart: unless-stopped